/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay_bis_service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import de.timowolfinger.liferay_bis_service.model.voelkerentwicklung;
import de.timowolfinger.liferay_bis_service.model.voelkerentwicklungModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the voelkerentwicklung service. Represents a row in the &quot;voelkerentwicklung&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>voelkerentwicklungModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link voelkerentwicklungImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see voelkerentwicklungImpl
 * @generated
 */
public class voelkerentwicklungModelImpl
	extends BaseModelImpl<voelkerentwicklung>
	implements voelkerentwicklungModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a voelkerentwicklung model instance should use the <code>voelkerentwicklung</code> interface instead.
	 */
	public static final String TABLE_NAME = "voelkerentwicklung";

	public static final Object[][] TABLE_COLUMNS = {
		{"id", Types.BIGINT}, {"anzahl_bebrueteter_rahmen", Types.FLOAT},
		{"abschaetzung_anzahl_individuen", Types.BIGINT},
		{"bienenvolk_id", Types.BIGINT}, {"datum", Types.TIMESTAMP},
		{"stockwaage_ewicht_kg", Types.FLOAT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("anzahl_bebrueteter_rahmen", Types.FLOAT);
		TABLE_COLUMNS_MAP.put("abschaetzung_anzahl_individuen", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bienenvolk_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("datum", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("stockwaage_ewicht_kg", Types.FLOAT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table voelkerentwicklung (id LONG not null primary key,anzahl_bebrueteter_rahmen DOUBLE,abschaetzung_anzahl_individuen LONG,bienenvolk_id LONG,datum DATE null,stockwaage_ewicht_kg DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table voelkerentwicklung";

	public static final String ORDER_BY_JPQL =
		" ORDER BY voelkerentwicklung.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY voelkerentwicklung.id ASC";

	public static final String DATA_SOURCE = "extDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public voelkerentwicklungModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return voelkerentwicklung.class;
	}

	@Override
	public String getModelClassName() {
		return voelkerentwicklung.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<voelkerentwicklung, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<voelkerentwicklung, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<voelkerentwicklung, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((voelkerentwicklung)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<voelkerentwicklung, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<voelkerentwicklung, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(voelkerentwicklung)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<voelkerentwicklung, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<voelkerentwicklung, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, voelkerentwicklung>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			voelkerentwicklung.class.getClassLoader(), voelkerentwicklung.class,
			ModelWrapper.class);

		try {
			Constructor<voelkerentwicklung> constructor =
				(Constructor<voelkerentwicklung>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<voelkerentwicklung, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<voelkerentwicklung, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<voelkerentwicklung, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<voelkerentwicklung, Object>>();
		Map<String, BiConsumer<voelkerentwicklung, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<voelkerentwicklung, ?>>();

		attributeGetterFunctions.put("id", voelkerentwicklung::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<voelkerentwicklung, Long>)voelkerentwicklung::setId);
		attributeGetterFunctions.put(
			"anzahl_bebrueteter_rahmen",
			voelkerentwicklung::getAnzahl_bebrueteter_rahmen);
		attributeSetterBiConsumers.put(
			"anzahl_bebrueteter_rahmen",
			(BiConsumer<voelkerentwicklung, Float>)
				voelkerentwicklung::setAnzahl_bebrueteter_rahmen);
		attributeGetterFunctions.put(
			"abschaetzung_anzahl_individuen",
			voelkerentwicklung::getAbschaetzung_anzahl_individuen);
		attributeSetterBiConsumers.put(
			"abschaetzung_anzahl_individuen",
			(BiConsumer<voelkerentwicklung, Long>)
				voelkerentwicklung::setAbschaetzung_anzahl_individuen);
		attributeGetterFunctions.put(
			"bienenvolk_id", voelkerentwicklung::getBienenvolk_id);
		attributeSetterBiConsumers.put(
			"bienenvolk_id",
			(BiConsumer<voelkerentwicklung, Long>)
				voelkerentwicklung::setBienenvolk_id);
		attributeGetterFunctions.put("datum", voelkerentwicklung::getDatum);
		attributeSetterBiConsumers.put(
			"datum",
			(BiConsumer<voelkerentwicklung, Date>)voelkerentwicklung::setDatum);
		attributeGetterFunctions.put(
			"stockwaage_gewicht_kg",
			voelkerentwicklung::getStockwaage_gewicht_kg);
		attributeSetterBiConsumers.put(
			"stockwaage_gewicht_kg",
			(BiConsumer<voelkerentwicklung, Float>)
				voelkerentwicklung::setStockwaage_gewicht_kg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public float getAnzahl_bebrueteter_rahmen() {
		return _anzahl_bebrueteter_rahmen;
	}

	@Override
	public void setAnzahl_bebrueteter_rahmen(float anzahl_bebrueteter_rahmen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anzahl_bebrueteter_rahmen = anzahl_bebrueteter_rahmen;
	}

	@Override
	public long getAbschaetzung_anzahl_individuen() {
		return _abschaetzung_anzahl_individuen;
	}

	@Override
	public void setAbschaetzung_anzahl_individuen(
		long abschaetzung_anzahl_individuen) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_abschaetzung_anzahl_individuen = abschaetzung_anzahl_individuen;
	}

	@Override
	public long getBienenvolk_id() {
		return _bienenvolk_id;
	}

	@Override
	public void setBienenvolk_id(long bienenvolk_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bienenvolk_id = bienenvolk_id;
	}

	@Override
	public Date getDatum() {
		return _datum;
	}

	@Override
	public void setDatum(Date datum) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_datum = datum;
	}

	@Override
	public float getStockwaage_gewicht_kg() {
		return _stockwaage_gewicht_kg;
	}

	@Override
	public void setStockwaage_gewicht_kg(float stockwaage_gewicht_kg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stockwaage_gewicht_kg = stockwaage_gewicht_kg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, voelkerentwicklung.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public voelkerentwicklung toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, voelkerentwicklung>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		voelkerentwicklungImpl voelkerentwicklungImpl =
			new voelkerentwicklungImpl();

		voelkerentwicklungImpl.setId(getId());
		voelkerentwicklungImpl.setAnzahl_bebrueteter_rahmen(
			getAnzahl_bebrueteter_rahmen());
		voelkerentwicklungImpl.setAbschaetzung_anzahl_individuen(
			getAbschaetzung_anzahl_individuen());
		voelkerentwicklungImpl.setBienenvolk_id(getBienenvolk_id());
		voelkerentwicklungImpl.setDatum(getDatum());
		voelkerentwicklungImpl.setStockwaage_gewicht_kg(
			getStockwaage_gewicht_kg());

		voelkerentwicklungImpl.resetOriginalValues();

		return voelkerentwicklungImpl;
	}

	@Override
	public int compareTo(voelkerentwicklung voelkerentwicklung) {
		int value = 0;

		if (getId() < voelkerentwicklung.getId()) {
			value = -1;
		}
		else if (getId() > voelkerentwicklung.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof voelkerentwicklung)) {
			return false;
		}

		voelkerentwicklung voelkerentwicklung = (voelkerentwicklung)object;

		long primaryKey = voelkerentwicklung.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<voelkerentwicklung> toCacheModel() {
		voelkerentwicklungCacheModel voelkerentwicklungCacheModel =
			new voelkerentwicklungCacheModel();

		voelkerentwicklungCacheModel.id = getId();

		voelkerentwicklungCacheModel.anzahl_bebrueteter_rahmen =
			getAnzahl_bebrueteter_rahmen();

		voelkerentwicklungCacheModel.abschaetzung_anzahl_individuen =
			getAbschaetzung_anzahl_individuen();

		voelkerentwicklungCacheModel.bienenvolk_id = getBienenvolk_id();

		Date datum = getDatum();

		if (datum != null) {
			voelkerentwicklungCacheModel.datum = datum.getTime();
		}
		else {
			voelkerentwicklungCacheModel.datum = Long.MIN_VALUE;
		}

		voelkerentwicklungCacheModel.stockwaage_gewicht_kg =
			getStockwaage_gewicht_kg();

		return voelkerentwicklungCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<voelkerentwicklung, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<voelkerentwicklung, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<voelkerentwicklung, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((voelkerentwicklung)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<voelkerentwicklung, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<voelkerentwicklung, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<voelkerentwicklung, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((voelkerentwicklung)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, voelkerentwicklung>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _id;
	private float _anzahl_bebrueteter_rahmen;
	private long _abschaetzung_anzahl_individuen;
	private long _bienenvolk_id;
	private Date _datum;
	private float _stockwaage_gewicht_kg;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<voelkerentwicklung, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((voelkerentwicklung)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id", _id);
		_columnOriginalValues.put(
			"anzahl_bebrueteter_rahmen", _anzahl_bebrueteter_rahmen);
		_columnOriginalValues.put(
			"abschaetzung_anzahl_individuen", _abschaetzung_anzahl_individuen);
		_columnOriginalValues.put("bienenvolk_id", _bienenvolk_id);
		_columnOriginalValues.put("datum", _datum);
		_columnOriginalValues.put(
			"stockwaage_ewicht_kg", _stockwaage_gewicht_kg);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("stockwaage_ewicht_kg", "stockwaage_gewicht_kg");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id", 1L);

		columnBitmasks.put("anzahl_bebrueteter_rahmen", 2L);

		columnBitmasks.put("abschaetzung_anzahl_individuen", 4L);

		columnBitmasks.put("bienenvolk_id", 8L);

		columnBitmasks.put("datum", 16L);

		columnBitmasks.put("stockwaage_ewicht_kg", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private voelkerentwicklung _escapedModel;

}