/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import de.timowolfinger.liferay.beeInformationSystem.model.Voelkerentwicklung;
import de.timowolfinger.liferay.beeInformationSystem.service.VoelkerentwicklungLocalService;
import de.timowolfinger.liferay.beeInformationSystem.service.VoelkerentwicklungLocalServiceUtil;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.AblegerPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.BehandlungenPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.BeutemassePersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.BienenrassenPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.BienenvoelkerPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.FuetterungenPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.FuttermittelPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.GesundheitszeugnissePersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.HerstellerPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.HonigerntenPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.MedikamentePersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.TrachtenPersistence;
import de.timowolfinger.liferay.beeInformationSystem.service.persistence.VoelkerentwicklungPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the voelkerentwicklung local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link de.timowolfinger.liferay.beeInformationSystem.service.impl.VoelkerentwicklungLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see de.timowolfinger.liferay.beeInformationSystem.service.impl.VoelkerentwicklungLocalServiceImpl
 * @generated
 */
public abstract class VoelkerentwicklungLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   VoelkerentwicklungLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>VoelkerentwicklungLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>VoelkerentwicklungLocalServiceUtil</code>.
	 */

	/**
	 * Adds the voelkerentwicklung to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect VoelkerentwicklungLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param voelkerentwicklung the voelkerentwicklung
	 * @return the voelkerentwicklung that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Voelkerentwicklung addVoelkerentwicklung(
		Voelkerentwicklung voelkerentwicklung) {

		voelkerentwicklung.setNew(true);

		return voelkerentwicklungPersistence.update(voelkerentwicklung);
	}

	/**
	 * Creates a new voelkerentwicklung with the primary key. Does not add the voelkerentwicklung to the database.
	 *
	 * @param voelkerentwicklung_id the primary key for the new voelkerentwicklung
	 * @return the new voelkerentwicklung
	 */
	@Override
	@Transactional(enabled = false)
	public Voelkerentwicklung createVoelkerentwicklung(
		long voelkerentwicklung_id) {

		return voelkerentwicklungPersistence.create(voelkerentwicklung_id);
	}

	/**
	 * Deletes the voelkerentwicklung with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect VoelkerentwicklungLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param voelkerentwicklung_id the primary key of the voelkerentwicklung
	 * @return the voelkerentwicklung that was removed
	 * @throws PortalException if a voelkerentwicklung with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Voelkerentwicklung deleteVoelkerentwicklung(
			long voelkerentwicklung_id)
		throws PortalException {

		return voelkerentwicklungPersistence.remove(voelkerentwicklung_id);
	}

	/**
	 * Deletes the voelkerentwicklung from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect VoelkerentwicklungLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param voelkerentwicklung the voelkerentwicklung
	 * @return the voelkerentwicklung that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Voelkerentwicklung deleteVoelkerentwicklung(
		Voelkerentwicklung voelkerentwicklung) {

		return voelkerentwicklungPersistence.remove(voelkerentwicklung);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return voelkerentwicklungPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Voelkerentwicklung.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return voelkerentwicklungPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.VoelkerentwicklungModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return voelkerentwicklungPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.VoelkerentwicklungModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return voelkerentwicklungPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return voelkerentwicklungPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return voelkerentwicklungPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Voelkerentwicklung fetchVoelkerentwicklung(
		long voelkerentwicklung_id) {

		return voelkerentwicklungPersistence.fetchByPrimaryKey(
			voelkerentwicklung_id);
	}

	/**
	 * Returns the voelkerentwicklung with the primary key.
	 *
	 * @param voelkerentwicklung_id the primary key of the voelkerentwicklung
	 * @return the voelkerentwicklung
	 * @throws PortalException if a voelkerentwicklung with the primary key could not be found
	 */
	@Override
	public Voelkerentwicklung getVoelkerentwicklung(long voelkerentwicklung_id)
		throws PortalException {

		return voelkerentwicklungPersistence.findByPrimaryKey(
			voelkerentwicklung_id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			voelkerentwicklungLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Voelkerentwicklung.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"voelkerentwicklung_id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			voelkerentwicklungLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Voelkerentwicklung.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"voelkerentwicklung_id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			voelkerentwicklungLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Voelkerentwicklung.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"voelkerentwicklung_id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return voelkerentwicklungPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return voelkerentwicklungLocalService.deleteVoelkerentwicklung(
			(Voelkerentwicklung)persistedModel);
	}

	@Override
	public BasePersistence<Voelkerentwicklung> getBasePersistence() {
		return voelkerentwicklungPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return voelkerentwicklungPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the voelkerentwicklungs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.VoelkerentwicklungModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of voelkerentwicklungs
	 * @param end the upper bound of the range of voelkerentwicklungs (not inclusive)
	 * @return the range of voelkerentwicklungs
	 */
	@Override
	public List<Voelkerentwicklung> getVoelkerentwicklungs(int start, int end) {
		return voelkerentwicklungPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of voelkerentwicklungs.
	 *
	 * @return the number of voelkerentwicklungs
	 */
	@Override
	public int getVoelkerentwicklungsCount() {
		return voelkerentwicklungPersistence.countAll();
	}

	/**
	 * Updates the voelkerentwicklung in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect VoelkerentwicklungLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param voelkerentwicklung the voelkerentwicklung
	 * @return the voelkerentwicklung that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Voelkerentwicklung updateVoelkerentwicklung(
		Voelkerentwicklung voelkerentwicklung) {

		return voelkerentwicklungPersistence.update(voelkerentwicklung);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			VoelkerentwicklungLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		voelkerentwicklungLocalService =
			(VoelkerentwicklungLocalService)aopProxy;

		_setLocalServiceUtilService(voelkerentwicklungLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return VoelkerentwicklungLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Voelkerentwicklung.class;
	}

	protected String getModelClassName() {
		return Voelkerentwicklung.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				voelkerentwicklungPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		VoelkerentwicklungLocalService voelkerentwicklungLocalService) {

		try {
			Field field =
				VoelkerentwicklungLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, voelkerentwicklungLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AblegerPersistence ablegerPersistence;

	@Reference
	protected BehandlungenPersistence behandlungenPersistence;

	@Reference
	protected BeutemassePersistence beutemassePersistence;

	@Reference
	protected BienenrassenPersistence bienenrassenPersistence;

	@Reference
	protected BienenvoelkerPersistence bienenvoelkerPersistence;

	@Reference
	protected FuetterungenPersistence fuetterungenPersistence;

	@Reference
	protected FuttermittelPersistence futtermittelPersistence;

	@Reference
	protected GesundheitszeugnissePersistence gesundheitszeugnissePersistence;

	@Reference
	protected HerstellerPersistence herstellerPersistence;

	@Reference
	protected HonigerntenPersistence honigerntenPersistence;

	@Reference
	protected MedikamentePersistence medikamentePersistence;

	@Reference
	protected TrachtenPersistence trachtenPersistence;

	protected VoelkerentwicklungLocalService voelkerentwicklungLocalService;

	@Reference
	protected VoelkerentwicklungPersistence voelkerentwicklungPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}