/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import de.timowolfinger.liferay.beeInformationSystem.model.futtermittel;
import de.timowolfinger.liferay.beeInformationSystem.model.futtermittelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the futtermittel service. Represents a row in the &quot;futtermittel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>futtermittelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link futtermittelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see futtermittelImpl
 * @generated
 */
public class futtermittelModelImpl
	extends BaseModelImpl<futtermittel> implements futtermittelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a futtermittel model instance should use the <code>futtermittel</code> interface instead.
	 */
	public static final String TABLE_NAME = "futtermittel";

	public static final Object[][] TABLE_COLUMNS = {
		{"futtermittel_id", Types.BIGINT}, {"name", Types.VARCHAR},
		{"hersteller_id", Types.BIGINT}, {"gebindegroesse", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("futtermittel_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hersteller_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("gebindegroesse", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table futtermittel (futtermittel_id LONG not null primary key,name VARCHAR(75) null,hersteller_id LONG,gebindegroesse VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table futtermittel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY futtermittel.futtermittel_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY futtermittel.futtermittel_id ASC";

	public static final String DATA_SOURCE = "extDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FUTTERMITTEL_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public futtermittelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _futtermittel_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFuttermittel_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _futtermittel_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return futtermittel.class;
	}

	@Override
	public String getModelClassName() {
		return futtermittel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<futtermittel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<futtermittel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<futtermittel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((futtermittel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<futtermittel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<futtermittel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(futtermittel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<futtermittel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<futtermittel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<futtermittel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<futtermittel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<futtermittel, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<futtermittel, Object>>();
		Map<String, BiConsumer<futtermittel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<futtermittel, ?>>();

		attributeGetterFunctions.put(
			"futtermittel_id", futtermittel::getFuttermittel_id);
		attributeSetterBiConsumers.put(
			"futtermittel_id",
			(BiConsumer<futtermittel, Long>)futtermittel::setFuttermittel_id);
		attributeGetterFunctions.put("name", futtermittel::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<futtermittel, String>)futtermittel::setName);
		attributeGetterFunctions.put(
			"hersteller_id", futtermittel::getHersteller_id);
		attributeSetterBiConsumers.put(
			"hersteller_id",
			(BiConsumer<futtermittel, Long>)futtermittel::setHersteller_id);
		attributeGetterFunctions.put(
			"gebindegroesse", futtermittel::getGebindegroesse);
		attributeSetterBiConsumers.put(
			"gebindegroesse",
			(BiConsumer<futtermittel, String>)futtermittel::setGebindegroesse);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getFuttermittel_id() {
		return _futtermittel_id;
	}

	@Override
	public void setFuttermittel_id(long futtermittel_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_futtermittel_id = futtermittel_id;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@Override
	public long getHersteller_id() {
		return _hersteller_id;
	}

	@Override
	public void setHersteller_id(long hersteller_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hersteller_id = hersteller_id;
	}

	@Override
	public String getGebindegroesse() {
		if (_gebindegroesse == null) {
			return "";
		}
		else {
			return _gebindegroesse;
		}
	}

	@Override
	public void setGebindegroesse(String gebindegroesse) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gebindegroesse = gebindegroesse;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, futtermittel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public futtermittel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, futtermittel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		futtermittelImpl futtermittelImpl = new futtermittelImpl();

		futtermittelImpl.setFuttermittel_id(getFuttermittel_id());
		futtermittelImpl.setName(getName());
		futtermittelImpl.setHersteller_id(getHersteller_id());
		futtermittelImpl.setGebindegroesse(getGebindegroesse());

		futtermittelImpl.resetOriginalValues();

		return futtermittelImpl;
	}

	@Override
	public futtermittel cloneWithOriginalValues() {
		futtermittelImpl futtermittelImpl = new futtermittelImpl();

		futtermittelImpl.setFuttermittel_id(
			this.<Long>getColumnOriginalValue("futtermittel_id"));
		futtermittelImpl.setName(this.<String>getColumnOriginalValue("name"));
		futtermittelImpl.setHersteller_id(
			this.<Long>getColumnOriginalValue("hersteller_id"));
		futtermittelImpl.setGebindegroesse(
			this.<String>getColumnOriginalValue("gebindegroesse"));

		return futtermittelImpl;
	}

	@Override
	public int compareTo(futtermittel futtermittel) {
		int value = 0;

		if (getFuttermittel_id() < futtermittel.getFuttermittel_id()) {
			value = -1;
		}
		else if (getFuttermittel_id() > futtermittel.getFuttermittel_id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof futtermittel)) {
			return false;
		}

		futtermittel futtermittel = (futtermittel)object;

		long primaryKey = futtermittel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<futtermittel> toCacheModel() {
		futtermittelCacheModel futtermittelCacheModel =
			new futtermittelCacheModel();

		futtermittelCacheModel.futtermittel_id = getFuttermittel_id();

		futtermittelCacheModel.name = getName();

		String name = futtermittelCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			futtermittelCacheModel.name = null;
		}

		futtermittelCacheModel.hersteller_id = getHersteller_id();

		futtermittelCacheModel.gebindegroesse = getGebindegroesse();

		String gebindegroesse = futtermittelCacheModel.gebindegroesse;

		if ((gebindegroesse != null) && (gebindegroesse.length() == 0)) {
			futtermittelCacheModel.gebindegroesse = null;
		}

		return futtermittelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<futtermittel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<futtermittel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<futtermittel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((futtermittel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<futtermittel, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<futtermittel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<futtermittel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((futtermittel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, futtermittel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					futtermittel.class, ModelWrapper.class);

	}

	private long _futtermittel_id;
	private String _name;
	private long _hersteller_id;
	private String _gebindegroesse;

	public <T> T getColumnValue(String columnName) {
		Function<futtermittel, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((futtermittel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("futtermittel_id", _futtermittel_id);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("hersteller_id", _hersteller_id);
		_columnOriginalValues.put("gebindegroesse", _gebindegroesse);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("futtermittel_id", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("hersteller_id", 4L);

		columnBitmasks.put("gebindegroesse", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private futtermittel _escapedModel;

}