/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import de.timowolfinger.liferay.beeInformationSystem.model.honigernten;
import de.timowolfinger.liferay.beeInformationSystem.model.honigerntenModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the honigernten service. Represents a row in the &quot;honigernten&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>honigerntenModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link honigerntenImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see honigerntenImpl
 * @generated
 */
@JSON(strict = true)
public class honigerntenModelImpl
	extends BaseModelImpl<honigernten> implements honigerntenModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a honigernten model instance should use the <code>honigernten</code> interface instead.
	 */
	public static final String TABLE_NAME = "honigernten";

	public static final Object[][] TABLE_COLUMNS = {
		{"honigernten_id", Types.BIGINT}, {"erntedatum", Types.TIMESTAMP},
		{"erntemenge_kg", Types.INTEGER}, {"bienenvolk_id", Types.BIGINT},
		{"tracht_id", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("honigernten_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("erntedatum", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("erntemenge_kg", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("bienenvolk_id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tracht_id", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table honigernten (honigernten_id LONG not null primary key,erntedatum DATE null,erntemenge_kg INTEGER,bienenvolk_id LONG,tracht_id LONG)";

	public static final String TABLE_SQL_DROP = "drop table honigernten";

	public static final String ORDER_BY_JPQL =
		" ORDER BY honigernten.honigernten_id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY honigernten.honigernten_id ASC";

	public static final String DATA_SOURCE = "extDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long HONIGERNTEN_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public honigerntenModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _honigernten_id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHonigernten_id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _honigernten_id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return honigernten.class;
	}

	@Override
	public String getModelClassName() {
		return honigernten.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<honigernten, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<honigernten, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<honigernten, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((honigernten)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<honigernten, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<honigernten, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(honigernten)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<honigernten, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<honigernten, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<honigernten, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<honigernten, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<honigernten, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<honigernten, Object>>();
		Map<String, BiConsumer<honigernten, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<honigernten, ?>>();

		attributeGetterFunctions.put(
			"honigernten_id", honigernten::getHonigernten_id);
		attributeSetterBiConsumers.put(
			"honigernten_id",
			(BiConsumer<honigernten, Long>)honigernten::setHonigernten_id);
		attributeGetterFunctions.put("erntedatum", honigernten::getErntedatum);
		attributeSetterBiConsumers.put(
			"erntedatum",
			(BiConsumer<honigernten, Date>)honigernten::setErntedatum);
		attributeGetterFunctions.put(
			"erntemenge_kg", honigernten::getErntemenge_kg);
		attributeSetterBiConsumers.put(
			"erntemenge_kg",
			(BiConsumer<honigernten, Integer>)honigernten::setErntemenge_kg);
		attributeGetterFunctions.put(
			"bienenvolk_id", honigernten::getBienenvolk_id);
		attributeSetterBiConsumers.put(
			"bienenvolk_id",
			(BiConsumer<honigernten, Long>)honigernten::setBienenvolk_id);
		attributeGetterFunctions.put("tracht_id", honigernten::getTracht_id);
		attributeSetterBiConsumers.put(
			"tracht_id",
			(BiConsumer<honigernten, Long>)honigernten::setTracht_id);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getHonigernten_id() {
		return _honigernten_id;
	}

	@Override
	public void setHonigernten_id(long honigernten_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_honigernten_id = honigernten_id;
	}

	@JSON
	@Override
	public Date getErntedatum() {
		return _erntedatum;
	}

	@Override
	public void setErntedatum(Date erntedatum) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_erntedatum = erntedatum;
	}

	@JSON
	@Override
	public int getErntemenge_kg() {
		return _erntemenge_kg;
	}

	@Override
	public void setErntemenge_kg(int erntemenge_kg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_erntemenge_kg = erntemenge_kg;
	}

	@JSON
	@Override
	public long getBienenvolk_id() {
		return _bienenvolk_id;
	}

	@Override
	public void setBienenvolk_id(long bienenvolk_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bienenvolk_id = bienenvolk_id;
	}

	@JSON
	@Override
	public long getTracht_id() {
		return _tracht_id;
	}

	@Override
	public void setTracht_id(long tracht_id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tracht_id = tracht_id;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, honigernten.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public honigernten toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, honigernten>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		honigerntenImpl honigerntenImpl = new honigerntenImpl();

		honigerntenImpl.setHonigernten_id(getHonigernten_id());
		honigerntenImpl.setErntedatum(getErntedatum());
		honigerntenImpl.setErntemenge_kg(getErntemenge_kg());
		honigerntenImpl.setBienenvolk_id(getBienenvolk_id());
		honigerntenImpl.setTracht_id(getTracht_id());

		honigerntenImpl.resetOriginalValues();

		return honigerntenImpl;
	}

	@Override
	public honigernten cloneWithOriginalValues() {
		honigerntenImpl honigerntenImpl = new honigerntenImpl();

		honigerntenImpl.setHonigernten_id(
			this.<Long>getColumnOriginalValue("honigernten_id"));
		honigerntenImpl.setErntedatum(
			this.<Date>getColumnOriginalValue("erntedatum"));
		honigerntenImpl.setErntemenge_kg(
			this.<Integer>getColumnOriginalValue("erntemenge_kg"));
		honigerntenImpl.setBienenvolk_id(
			this.<Long>getColumnOriginalValue("bienenvolk_id"));
		honigerntenImpl.setTracht_id(
			this.<Long>getColumnOriginalValue("tracht_id"));

		return honigerntenImpl;
	}

	@Override
	public int compareTo(honigernten honigernten) {
		int value = 0;

		if (getHonigernten_id() < honigernten.getHonigernten_id()) {
			value = -1;
		}
		else if (getHonigernten_id() > honigernten.getHonigernten_id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof honigernten)) {
			return false;
		}

		honigernten honigernten = (honigernten)object;

		long primaryKey = honigernten.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<honigernten> toCacheModel() {
		honigerntenCacheModel honigerntenCacheModel =
			new honigerntenCacheModel();

		honigerntenCacheModel.honigernten_id = getHonigernten_id();

		Date erntedatum = getErntedatum();

		if (erntedatum != null) {
			honigerntenCacheModel.erntedatum = erntedatum.getTime();
		}
		else {
			honigerntenCacheModel.erntedatum = Long.MIN_VALUE;
		}

		honigerntenCacheModel.erntemenge_kg = getErntemenge_kg();

		honigerntenCacheModel.bienenvolk_id = getBienenvolk_id();

		honigerntenCacheModel.tracht_id = getTracht_id();

		return honigerntenCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<honigernten, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<honigernten, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<honigernten, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((honigernten)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<honigernten, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<honigernten, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<honigernten, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((honigernten)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, honigernten>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					honigernten.class, ModelWrapper.class);

	}

	private long _honigernten_id;
	private Date _erntedatum;
	private int _erntemenge_kg;
	private long _bienenvolk_id;
	private long _tracht_id;

	public <T> T getColumnValue(String columnName) {
		Function<honigernten, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((honigernten)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("honigernten_id", _honigernten_id);
		_columnOriginalValues.put("erntedatum", _erntedatum);
		_columnOriginalValues.put("erntemenge_kg", _erntemenge_kg);
		_columnOriginalValues.put("bienenvolk_id", _bienenvolk_id);
		_columnOriginalValues.put("tracht_id", _tracht_id);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("honigernten_id", 1L);

		columnBitmasks.put("erntedatum", 2L);

		columnBitmasks.put("erntemenge_kg", 4L);

		columnBitmasks.put("bienenvolk_id", 8L);

		columnBitmasks.put("tracht_id", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private honigernten _escapedModel;

}