/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Gesundheitszeugnis service. Represents a row in the &quot;gesundheitszeugnis&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.GesundheitszeugnisModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.GesundheitszeugnisImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Gesundheitszeugnis
 * @generated
 */
@ProviderType
public interface GesundheitszeugnisModel extends BaseModel<Gesundheitszeugnis> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gesundheitszeugnis model instance should use the {@link Gesundheitszeugnis} interface instead.
	 */

	/**
	 * Returns the primary key of this gesundheitszeugnis.
	 *
	 * @return the primary key of this gesundheitszeugnis
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gesundheitszeugnis.
	 *
	 * @param primaryKey the primary key of this gesundheitszeugnis
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gesundheitszeugnis_id of this gesundheitszeugnis.
	 *
	 * @return the gesundheitszeugnis_id of this gesundheitszeugnis
	 */
	public long getGesundheitszeugnis_id();

	/**
	 * Sets the gesundheitszeugnis_id of this gesundheitszeugnis.
	 *
	 * @param gesundheitszeugnis_id the gesundheitszeugnis_id of this gesundheitszeugnis
	 */
	public void setGesundheitszeugnis_id(long gesundheitszeugnis_id);

	/**
	 * Returns the seriennummer_lt_form of this gesundheitszeugnis.
	 *
	 * @return the seriennummer_lt_form of this gesundheitszeugnis
	 */
	@AutoEscape
	public String getSeriennummer_lt_form();

	/**
	 * Sets the seriennummer_lt_form of this gesundheitszeugnis.
	 *
	 * @param seriennummer_lt_form the seriennummer_lt_form of this gesundheitszeugnis
	 */
	public void setSeriennummer_lt_form(String seriennummer_lt_form);

	/**
	 * Returns the dokument of this gesundheitszeugnis.
	 *
	 * @return the dokument of this gesundheitszeugnis
	 */
	@AutoEscape
	public String getDokument();

	/**
	 * Sets the dokument of this gesundheitszeugnis.
	 *
	 * @param dokument the dokument of this gesundheitszeugnis
	 */
	public void setDokument(String dokument);

	/**
	 * Returns the ausstellungsdatum of this gesundheitszeugnis.
	 *
	 * @return the ausstellungsdatum of this gesundheitszeugnis
	 */
	public Date getAusstellungsdatum();

	/**
	 * Sets the ausstellungsdatum of this gesundheitszeugnis.
	 *
	 * @param ausstellungsdatum the ausstellungsdatum of this gesundheitszeugnis
	 */
	public void setAusstellungsdatum(Date ausstellungsdatum);

	/**
	 * Returns the dokument_dateityp of this gesundheitszeugnis.
	 *
	 * @return the dokument_dateityp of this gesundheitszeugnis
	 */
	@AutoEscape
	public String getDokument_dateityp();

	/**
	 * Sets the dokument_dateityp of this gesundheitszeugnis.
	 *
	 * @param dokument_dateityp the dokument_dateityp of this gesundheitszeugnis
	 */
	public void setDokument_dateityp(String dokument_dateityp);

	@Override
	public Gesundheitszeugnis cloneWithOriginalValues();

}