/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Honigernte service. Represents a row in the &quot;honigernte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.HonigernteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.HonigernteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Honigernte
 * @generated
 */
@ProviderType
public interface HonigernteModel extends BaseModel<Honigernte> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a honigernte model instance should use the {@link Honigernte} interface instead.
	 */

	/**
	 * Returns the primary key of this honigernte.
	 *
	 * @return the primary key of this honigernte
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this honigernte.
	 *
	 * @param primaryKey the primary key of this honigernte
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the honigernte_id of this honigernte.
	 *
	 * @return the honigernte_id of this honigernte
	 */
	public long getHonigernte_id();

	/**
	 * Sets the honigernte_id of this honigernte.
	 *
	 * @param honigernte_id the honigernte_id of this honigernte
	 */
	public void setHonigernte_id(long honigernte_id);

	/**
	 * Returns the erntedatum of this honigernte.
	 *
	 * @return the erntedatum of this honigernte
	 */
	public Date getErntedatum();

	/**
	 * Sets the erntedatum of this honigernte.
	 *
	 * @param erntedatum the erntedatum of this honigernte
	 */
	public void setErntedatum(Date erntedatum);

	/**
	 * Returns the erntemenge_kg of this honigernte.
	 *
	 * @return the erntemenge_kg of this honigernte
	 */
	public int getErntemenge_kg();

	/**
	 * Sets the erntemenge_kg of this honigernte.
	 *
	 * @param erntemenge_kg the erntemenge_kg of this honigernte
	 */
	public void setErntemenge_kg(int erntemenge_kg);

	/**
	 * Returns the bienenvolk_id of this honigernte.
	 *
	 * @return the bienenvolk_id of this honigernte
	 */
	public long getBienenvolk_id();

	/**
	 * Sets the bienenvolk_id of this honigernte.
	 *
	 * @param bienenvolk_id the bienenvolk_id of this honigernte
	 */
	public void setBienenvolk_id(long bienenvolk_id);

	/**
	 * Returns the tracht_id of this honigernte.
	 *
	 * @return the tracht_id of this honigernte
	 */
	public long getTracht_id();

	/**
	 * Sets the tracht_id of this honigernte.
	 *
	 * @param tracht_id the tracht_id of this honigernte
	 */
	public void setTracht_id(long tracht_id);

	@Override
	public Honigernte cloneWithOriginalValues();

}