/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay.beeInformationSystem.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Medikament service. Represents a row in the &quot;medikament&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.MedikamentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.timowolfinger.liferay.beeInformationSystem.model.impl.MedikamentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Medikament
 * @generated
 */
@ProviderType
public interface MedikamentModel extends BaseModel<Medikament> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a medikament model instance should use the {@link Medikament} interface instead.
	 */

	/**
	 * Returns the primary key of this medikament.
	 *
	 * @return the primary key of this medikament
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this medikament.
	 *
	 * @param primaryKey the primary key of this medikament
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the medikament_id of this medikament.
	 *
	 * @return the medikament_id of this medikament
	 */
	public long getMedikament_id();

	/**
	 * Sets the medikament_id of this medikament.
	 *
	 * @param medikament_id the medikament_id of this medikament
	 */
	public void setMedikament_id(long medikament_id);

	/**
	 * Returns the name of this medikament.
	 *
	 * @return the name of this medikament
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this medikament.
	 *
	 * @param name the name of this medikament
	 */
	public void setName(String name);

	/**
	 * Returns the hersteller_id of this medikament.
	 *
	 * @return the hersteller_id of this medikament
	 */
	public long getHersteller_id();

	/**
	 * Sets the hersteller_id of this medikament.
	 *
	 * @param hersteller_id the hersteller_id of this medikament
	 */
	public void setHersteller_id(long hersteller_id);

	/**
	 * Returns the dosierung of this medikament.
	 *
	 * @return the dosierung of this medikament
	 */
	@AutoEscape
	public String getDosierung();

	/**
	 * Sets the dosierung of this medikament.
	 *
	 * @param dosierung the dosierung of this medikament
	 */
	public void setDosierung(String dosierung);

	@Override
	public Medikament cloneWithOriginalValues();

}