/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package de.timowolfinger.liferay_bis_service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the beutemasse service. Represents a row in the &quot;beutemasse&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>de.timowolfinger.liferay_bis_service.model.impl.beutemasseModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>de.timowolfinger.liferay_bis_service.model.impl.beutemasseImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see beutemasse
 * @generated
 */
@ProviderType
public interface beutemasseModel extends BaseModel<beutemasse> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a beutemasse model instance should use the {@link beutemasse} interface instead.
	 */

	/**
	 * Returns the primary key of this beutemasse.
	 *
	 * @return the primary key of this beutemasse
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this beutemasse.
	 *
	 * @param primaryKey the primary key of this beutemasse
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this beutemasse.
	 *
	 * @return the ID of this beutemasse
	 */
	public long getId();

	/**
	 * Sets the ID of this beutemasse.
	 *
	 * @param id the ID of this beutemasse
	 */
	public void setId(long id);

	/**
	 * Returns the name of this beutemasse.
	 *
	 * @return the name of this beutemasse
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this beutemasse.
	 *
	 * @param name the name of this beutemasse
	 */
	public void setName(String name);

}